/**
 * 예외처리1 try catch
 */
try {
  printMessage('hello');
} catch (e) {
  console.log('error:', e);
}

console.log('program finished');
